from .countdown import Countdown
from .zalgo import Zalgo
from .flip import Flip
from .about import About
from .xkcd import XKCD
from .hearts import Hearts
from .spaces import Spaces
from .applause import Applause
from .chat import Chat
from .weather import Weather
from .insult import Insult
from .love import Love
from .chose import Chose
from .eightball import EightBall
from .analytics import Analytics
from .pick import Pick
from .meme import Meme
from .system import Welcome
from .youtube import YouTube
from .price import Price
from .minion import Minion
from .house import House
from .location import Location
from .lyrics import Lyrics
from .nasa import NASA
from .twitter import Twitter
from .tea import Tea
from .conversationstarter import ConversationStarter
from .quote import Quote
from .dog import Dog
from .funfact import FunFact
from .funny import Funny
from .boink import Boink
